// This file was generated by FlutterFire CLI
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions? get currentPlatform {
    if (kIsWeb) {
      // Web configuration
      return FirebaseOptions(
        apiKey: "YOUR_WEB_API_KEY",
        appId: "YOUR_WEB_APP_ID",
        messagingSenderId: "YOUR_WEB_MESSAGING_SENDER_ID",
        projectId: "YOUR_PROJECT_ID",
      );
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
      // Android configuration
        return FirebaseOptions(
          apiKey: "AIzaSyBG0N43dT-xRucKGeQgXWP1TBaaojWsz28", // current_key
          appId: "1:292665976187:android:7766d911a33e8c0ed549de", // mobilesdk_app_id
          messagingSenderId: "292665976187", // project_number
          projectId: "sportm8s-aca03", // project_id
          storageBucket: "sportm8s-aca03.firebasestorage.app", // storage_bucket
        );
        /*
      case TargetPlatform.iOS:
      // iOS configuration
        return FirebaseOptions(
          apiKey: "YOUR_IOS_API_KEY",
          appId: "YOUR_IOS_APP_ID",
          messagingSenderId: "YOUR_IOS_MESSAGING_SENDER_ID",
          projectId: "YOUR_PROJECT_ID",
        );
      case TargetPlatform.macOS:
      // macOS configuration
        return FirebaseOptions(
          apiKey: "YOUR_MACOS_API_KEY",
          appId: "YOUR_MACOS_APP_ID",
          messagingSenderId: "YOUR_MACOS_MESSAGING_SENDER_ID",
          projectId: "YOUR_PROJECT_ID",
        );
        */
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.');
    }
  }
}